-- Studio Las OS 9.0 - read-only audit for public.clients INSERT RLS
-- This file is intentionally read-only. It uses SELECT / catalog reads only.
-- It does not SET role/claims, INSERT, UPDATE, DELETE, GRANT, CREATE, DROP, or ALTER.
--
-- Run it in Supabase SQL Editor after setting the same authenticated test
-- context in a previous statement, or run it directly to inspect live DDL/RLS.

select
  '00_runtime_context' as audit_section,
  current_user,
  session_user,
  current_setting('role', true) as active_role_setting,
  current_setting('request.jwt.claim.sub', true) as jwt_claim_sub,
  current_setting('request.jwt.claim.role', true) as jwt_claim_role,
  current_setting('request.jwt.claims', true) as jwt_claims,
  auth.uid() as auth_uid;

select
  '01_clients_table_flags' as audit_section,
  n.nspname as schema_name,
  c.relname as table_name,
  pg_get_userbyid(c.relowner) as table_owner,
  c.relrowsecurity as rls_enabled,
  c.relforcerowsecurity as force_rls,
  row_security_active(c.oid) as row_security_active_for_current_role,
  c.relkind,
  c.relacl
from pg_class c
join pg_namespace n on n.oid = c.relnamespace
where n.nspname = 'public'
  and c.relname = 'clients';

select
  '02_clients_reconstructed_ddl' as audit_section,
  format(
    'create table %I.%I (%s%s%s);',
    n.nspname,
    c.relname,
    coalesce((
      select string_agg(
        format(
          E'\n  %I %s%s%s%s%s',
          a.attname,
          pg_catalog.format_type(a.atttypid, a.atttypmod),
          case
            when a.attidentity = 'a' then ' generated always as identity'
            when a.attidentity = 'd' then ' generated by default as identity'
            else ''
          end,
          case
            when a.attgenerated <> '' then ' generated always as (' || pg_get_expr(d.adbin, d.adrelid) || ') stored'
            when d.adbin is not null and a.attidentity = '' then ' default ' || pg_get_expr(d.adbin, d.adrelid)
            else ''
          end,
          case when a.attnotnull then ' not null' else '' end,
          case when a.attcollation <> t.typcollation and a.attcollation <> 0 then ' collate ' || quote_ident(coll.collname) else '' end
        ),
        ','
        order by a.attnum
      )
      from pg_attribute a
      join pg_type t on t.oid = a.atttypid
      left join pg_attrdef d on d.adrelid = a.attrelid and d.adnum = a.attnum
      left join pg_collation coll on coll.oid = a.attcollation
      where a.attrelid = c.oid
        and a.attnum > 0
        and not a.attisdropped
    ), ''),
    coalesce((
      select string_agg(
        format(E',\n  constraint %I %s', con.conname, pg_get_constraintdef(con.oid, true)),
        ''
        order by con.conname
      )
      from pg_constraint con
      where con.conrelid = c.oid
    ), ''),
    E'\n'
  ) as reconstructed_ddl
from pg_class c
join pg_namespace n on n.oid = c.relnamespace
where n.nspname = 'public'
  and c.relname = 'clients';

select
  '03_clients_columns' as audit_section,
  a.attnum,
  a.attname as column_name,
  pg_catalog.format_type(a.atttypid, a.atttypmod) as data_type,
  a.attnotnull as not_null,
  a.attidentity as identity_kind,
  a.attgenerated as generated_kind,
  pg_get_expr(d.adbin, d.adrelid) as default_expression,
  col_description(a.attrelid, a.attnum) as column_comment
from pg_class c
join pg_namespace n on n.oid = c.relnamespace
join pg_attribute a on a.attrelid = c.oid
left join pg_attrdef d on d.adrelid = a.attrelid and d.adnum = a.attnum
where n.nspname = 'public'
  and c.relname = 'clients'
  and a.attnum > 0
  and not a.attisdropped
order by a.attnum;

select
  '04_clients_required_columns_without_defaults' as audit_section,
  a.attname as column_name,
  pg_catalog.format_type(a.atttypid, a.atttypmod) as data_type
from pg_class c
join pg_namespace n on n.oid = c.relnamespace
join pg_attribute a on a.attrelid = c.oid
left join pg_attrdef d on d.adrelid = a.attrelid and d.adnum = a.attnum
where n.nspname = 'public'
  and c.relname = 'clients'
  and a.attnum > 0
  and not a.attisdropped
  and a.attnotnull
  and d.adbin is null
  and a.attidentity = ''
  and a.attgenerated = ''
order by a.attnum;

select
  '05_clients_constraints' as audit_section,
  con.conname as constraint_name,
  con.contype as constraint_type,
  con.convalidated as validated,
  con.condeferrable as deferrable,
  con.condeferred as initially_deferred,
  pg_get_constraintdef(con.oid, true) as constraint_definition
from pg_constraint con
join pg_class c on c.oid = con.conrelid
join pg_namespace n on n.oid = c.relnamespace
where n.nspname = 'public'
  and c.relname = 'clients'
order by con.contype, con.conname;

select
  '06_clients_foreign_keys' as audit_section,
  con.conname as constraint_name,
  con.convalidated as validated,
  con.condeferrable as deferrable,
  con.condeferred as initially_deferred,
  con.confrelid::regclass as referenced_table,
  pg_get_constraintdef(con.oid, true) as foreign_key_definition
from pg_constraint con
join pg_class c on c.oid = con.conrelid
join pg_namespace n on n.oid = c.relnamespace
where n.nspname = 'public'
  and c.relname = 'clients'
  and con.contype = 'f'
order by con.conname;

select
  '07_clients_triggers' as audit_section,
  t.tgname as trigger_name,
  t.tgenabled as enabled_state,
  (t.tgtype::int & 1) = 1 as for_each_row,
  (t.tgtype::int & 2) = 2 as is_before,
  (t.tgtype::int & 4) = 4 as on_insert,
  (t.tgtype::int & 8) = 8 as on_delete,
  (t.tgtype::int & 16) = 16 as on_update,
  (t.tgtype::int & 32) = 32 as on_truncate,
  t.tgisinternal as is_internal,
  pg_get_triggerdef(t.oid, true) as trigger_definition
from pg_trigger t
join pg_class c on c.oid = t.tgrelid
join pg_namespace n on n.oid = c.relnamespace
where n.nspname = 'public'
  and c.relname = 'clients'
order by t.tgname;

select
  '08_clients_policies' as audit_section,
  p.polname as policy_name,
  case p.polcmd
    when 'r' then 'SELECT'
    when 'a' then 'INSERT'
    when 'w' then 'UPDATE'
    when 'd' then 'DELETE'
    when '*' then 'ALL'
    else p.polcmd::text
  end as command,
  case when p.polpermissive then 'PERMISSIVE' else 'RESTRICTIVE' end as policy_mode,
  case
    when p.polroles = '{0}'::oid[] then array['public']
    else (
      select array_agg(r.rolname order by r.rolname)
      from unnest(p.polroles) role_oid
      join pg_roles r on r.oid = role_oid
    )
  end as policy_roles,
  pg_get_expr(p.polqual, p.polrelid) as qual,
  pg_get_expr(p.polwithcheck, p.polrelid) as with_check
from pg_policy p
join pg_class c on c.oid = p.polrelid
join pg_namespace n on n.oid = c.relnamespace
where n.nspname = 'public'
  and c.relname = 'clients'
order by p.polcmd, p.polname;

select
  '09_clients_restrictive_policies' as audit_section,
  p.polname as policy_name,
  p.polcmd as command,
  pg_get_expr(p.polqual, p.polrelid) as qual,
  pg_get_expr(p.polwithcheck, p.polrelid) as with_check
from pg_policy p
join pg_class c on c.oid = p.polrelid
join pg_namespace n on n.oid = c.relnamespace
where n.nspname = 'public'
  and c.relname = 'clients'
  and p.polpermissive is false
order by p.polcmd, p.polname;

select
  '10_clients_table_grants' as audit_section,
  grantee,
  privilege_type,
  is_grantable,
  with_hierarchy
from information_schema.table_privileges
where table_schema = 'public'
  and table_name = 'clients'
  and grantee in ('authenticated', 'anon', 'public')
order by grantee, privilege_type;

select
  '11_clients_column_grants' as audit_section,
  grantee,
  column_name,
  privilege_type,
  is_grantable
from information_schema.column_privileges
where table_schema = 'public'
  and table_name = 'clients'
  and grantee in ('authenticated', 'anon', 'public')
order by grantee, column_name, privilege_type;

select
  '12_clients_has_table_privilege' as audit_section,
  role_name,
  has_table_privilege(role_name, 'public.clients', 'SELECT') as can_select,
  has_table_privilege(role_name, 'public.clients', 'INSERT') as can_insert,
  has_table_privilege(role_name, 'public.clients', 'UPDATE') as can_update,
  has_table_privilege(role_name, 'public.clients', 'DELETE') as can_delete
from (values ('authenticated'), ('anon'), ('public')) as roles(role_name);

select
  '13_clients_sequence_grants' as audit_section,
  linked_column,
  sequence_name,
  case when sequence_name is null then null else has_sequence_privilege('authenticated', sequence_name, 'USAGE') end as authenticated_usage,
  case when sequence_name is null then null else has_sequence_privilege('authenticated', sequence_name, 'SELECT') end as authenticated_select,
  case when sequence_name is null then null else has_sequence_privilege('anon', sequence_name, 'USAGE') end as anon_usage,
  case when sequence_name is null then null else has_sequence_privilege('anon', sequence_name, 'SELECT') end as anon_select
from (
  select
    a.attname as linked_column,
    pg_get_serial_sequence('public.clients', a.attname) as sequence_name
  from pg_class c
  join pg_namespace n on n.oid = c.relnamespace
  join pg_attribute a on a.attrelid = c.oid
  where n.nspname = 'public'
    and c.relname = 'clients'
    and a.attnum > 0
    and not a.attisdropped
) s
where sequence_name is not null
union all
select
  '13_clients_sequence_grants' as audit_section,
  'no linked sequences found' as linked_column,
  null::text as sequence_name,
  null::boolean,
  null::boolean,
  null::boolean,
  null::boolean
where not exists (
  select 1
  from pg_class c
  join pg_namespace n on n.oid = c.relnamespace
  join pg_attribute a on a.attrelid = c.oid
  where n.nspname = 'public'
    and c.relname = 'clients'
    and a.attnum > 0
    and not a.attisdropped
    and pg_get_serial_sequence('public.clients', a.attname) is not null
);

select
  '14_relevant_function_definitions' as audit_section,
  p.proname as function_name,
  pg_get_userbyid(p.proowner) as function_owner,
  p.prosecdef as security_definer,
  p.provolatile as volatility,
  p.proleakproof as leakproof,
  p.proconfig as function_config,
  p.proacl as function_acl,
  pg_get_functiondef(p.oid) as function_definition
from pg_proc p
join pg_namespace n on n.oid = p.pronamespace
where n.nspname = 'public'
  and p.proname in (
    'is_current_trainer_profile',
    'is_trainer',
    'current_profile_id',
    'trainer_can_access_client',
    'client_can_access_client'
  )
order by p.proname, p.oid;

select
  '15_current_helper_evaluation' as audit_section,
  auth.uid() as auth_uid,
  current_setting('request.jwt.claim.sub', true) as jwt_claim_sub,
  public.is_current_trainer_profile('11111111-1111-4111-8111-111111111111') as is_current_trainer_profile_target,
  public.is_trainer() as is_trainer,
  public.current_profile_id() as current_profile_id;

select
  '16_insert_policy_expression_eval_for_target_row' as audit_section,
  '11111111-1111-4111-8111-111111111111'::uuid as proposed_owner_trainer_id,
  null::timestamptz as proposed_deleted_at,
  public.is_current_trainer_profile('11111111-1111-4111-8111-111111111111') as insert_policy_008_eval,
  (null::timestamptz is null) as deleted_at_is_null_eval,
  (
    public.is_current_trainer_profile('11111111-1111-4111-8111-111111111111')
    and null::timestamptz is null
  ) as legacy_insert_policy_eval_with_deleted_at;

select
  '17_existing_clients_select_policy_helper_eval' as audit_section,
  c.id,
  c.owner_trainer_id,
  c.name,
  c.deleted_at,
  public.trainer_can_access_client(c.id) as trainer_can_access_client_eval
from public.clients c
where c.owner_trainer_id = '11111111-1111-4111-8111-111111111111'
order by c.created_at desc
limit 10;

select
  '18_mutating_probe_sql_not_executed' as audit_section,
  'Run these probes manually only after reviewing the audit. They are emitted as text and are not executed by this read-only file.' as note,
  $probe$
  -- Probe A: tests INSERT WITH CHECK without RETURNING.
  begin;
  set local role authenticated;
  select set_config('request.jwt.claim.sub', '277d6162-60cf-4263-80c8-8e0732749957', true);
  select set_config('request.jwt.claim.role', 'authenticated', true);
  select set_config('request.jwt.claims', '{"sub":"277d6162-60cf-4263-80c8-8e0732749957","role":"authenticated"}', true);
  insert into public.clients (owner_trainer_id, name, deleted_at)
  values ('11111111-1111-4111-8111-111111111111', 'RLS smoke test client no returning', null);
  rollback;

  -- Probe B: tests INSERT plus RETURNING / SELECT visibility.
  begin;
  set local role authenticated;
  select set_config('request.jwt.claim.sub', '277d6162-60cf-4263-80c8-8e0732749957', true);
  select set_config('request.jwt.claim.role', 'authenticated', true);
  select set_config('request.jwt.claims', '{"sub":"277d6162-60cf-4263-80c8-8e0732749957","role":"authenticated"}', true);
  insert into public.clients (owner_trainer_id, name, deleted_at)
  values ('11111111-1111-4111-8111-111111111111', 'RLS smoke test client returning', null)
  returning id, owner_trainer_id, name, deleted_at;
  rollback;

  -- Probe C: explicit all application-required columns plus RETURNING.
  begin;
  set local role authenticated;
  select set_config('request.jwt.claim.sub', '277d6162-60cf-4263-80c8-8e0732749957', true);
  select set_config('request.jwt.claim.role', 'authenticated', true);
  select set_config('request.jwt.claims', '{"sub":"277d6162-60cf-4263-80c8-8e0732749957","role":"authenticated"}', true);
  insert into public.clients (
    owner_trainer_id,
    name,
    stage,
    status,
    created_at,
    updated_at,
    deleted_at
  )
  values (
    '11111111-1111-4111-8111-111111111111',
    'RLS smoke explicit required client',
    1,
    'active',
    now(),
    now(),
    null
  )
  returning id, owner_trainer_id, name, stage, status, created_at, updated_at, deleted_at;
  rollback;
$probe$ as probe_sql;
