import assert from "node:assert/strict";
import { mkdir, writeFile } from "node:fs/promises";
import { chromium } from "playwright";
import { api, login } from "./attention_e2e_helpers.mjs";
const id="c7200000-0000-4000-8000-000000000001", dir=process.env.STUDIO_LAS_E2E_ARTIFACT_DIR;
const marker=process.env.STUDIO_LAS_E2E_MARKER;
const title=`Pierwsza wskazówka · ${marker}`;
const privateText=`Prywatna interpretacja PWD · ${marker}`;
const today=new Date().toISOString().slice(0,10), review=new Date(Date.now()+21*86400000).toISOString().slice(0,10);
await mkdir(dir,{recursive:true});
const browser=await chromium.launch();
const tc=await browser.newContext({viewport:{width:1440,height:1000}}), cc=await browser.newContext({viewport:{width:390,height:844}});
const t=await tc.newPage(), c=await cc.newPage();
try {
 const token=await login(t,process.env.STUDIO_LAS_QA_EMAIL,process.env.STUDIO_LAS_QA_PASSWORD,true);
 const clientToken=await login(c,"attention.client@example.test",process.env.STUDIO_LAS_ATTENTION_CLIENT_PASSWORD);
 const snapshot=()=>api("/rest/v1/rpc/client_portal_snapshot",clientToken,"POST",{});
 const before=await snapshot();
 await t.getByLabel("Wybierz klienta").selectOption(id);
 await t.getByText("Dostęp klienta do aplikacji: aktywny.",{exact:true}).waitFor();
 await t.locator("summary").filter({hasText:/^(Zapisz pierwszą wizytę diagnostyczną|Dodaj korektę pierwszej wizyty diagnostycznej)$/}).click();
 const pwd=t.locator('form').filter({has:t.locator('[name="realLifeGoal"]')});
 for(const [name,value] of Object.entries({date:today,realLifeGoal:"Swobodne wejście po schodach",whyImportant:"Samodzielność — dane fikcyjne",contextBoundaries:"Omówione granice — tylko trener",trainerInterpretation:privateText,nextStep:"Ustalić pierwszą wskazówkę"})) await pwd.locator(`[name="${name}"]`).fill(value);
 await pwd.locator('[name="trainerDecision"]').selectOption("continue_guidance");
 await pwd.locator('button[type="submit"]').click();
 await t.locator("section").filter({has:t.getByRole("heading",{name:"Pierwsza wizyta diagnostyczna",exact:true})}).getByText(privateText,{exact:false}).first().waitFor();
 assert.equal((await snapshot()).homePlan.id,before.homePlan.id,"PWD cannot publish guidance");
 await t.getByText("Przygotuj pierwszą wskazówkę z tej PWD",{exact:true}).click();
 const form=t.locator(".first-guidance-form");
 assert.ok((await form.locator('[name="focus"]').inputValue()).includes("Swobodne wejście po schodach"));
 assert.equal(await form.locator('[name="instructions"]').inputValue(),"");
 await form.locator('[name="title"]').fill(title);
 await form.locator('[name="frequency"]').fill("2 razy w tygodniu");
 await form.locator('[name="reviewDate"]').fill(review);
 await form.locator('[name="instructions"]').fill("Ustalenia z rozmowy. Pytania zgłaszaj osobno.");
 await form.screenshot({path:`${dir}/pwd-first-guidance-desktop.png`});
 await t.setViewportSize({width:390,height:844});assert.equal(await t.evaluate(()=>document.documentElement.scrollWidth>innerWidth+2),false);
 await form.screenshot({path:`${dir}/pwd-first-guidance-mobile.png`});
 await form.getByRole("button",{name:"Zapisz szkic pierwszej wskazówki",exact:true}).click();
 await t.locator(".guidance-record").filter({hasText:title}).waitFor();
 let plan=(await api(`/rest/v1/home_plans?client_id=eq.${id}&title=eq.${encodeURIComponent(title)}&select=*`,token))[0];
 assert.equal(plan.status,"draft");assert.equal(plan.published_at,null);assert.equal(plan.approved_at,null);
 assert.ok(plan.instructions.includes(review));assert.ok(!JSON.stringify(plan).includes(privateText));
 assert.equal((await snapshot()).homePlan.id,before.homePlan.id);
 await t.getByText("Dodaj działanie do szkicu",{exact:true}).click();
 const action=t.locator('form').filter({has:t.locator('[name="homePlanId"]')});
 await action.locator('[name="homePlanId"]').selectOption(plan.id);
 for(const [name,value] of Object.entries({name:"Ruch omówiony z trenerem",dosage:"2 spokojne powtórzenia",frequency:"2 razy w tygodniu",clientCue:"Zgodnie z demonstracją",stopCriteria:"Przerwij przy ustalonym sygnale"})) await action.locator(`[name="${name}"]`).fill(value);
 await action.locator('button[type="submit"]').click();
 await t.getByText("Ruch omówiony z trenerem",{exact:true}).waitFor();
 let card=t.locator(".guidance-record").filter({hasText:title});
 await card.getByRole("button",{name:"Zatwierdź tę treść do publikacji",exact:true}).click();
 await card.getByRole("button",{name:"Opublikuj jako aktualną wskazówkę",exact:true}).waitFor();
 assert.equal((await snapshot()).homePlan.id,before.homePlan.id,"Approval alone cannot publish");
 await card.getByRole("button",{name:"Opublikuj jako aktualną wskazówkę",exact:true}).click();
 await card.getByRole("button",{name:"Wycofaj wskazówkę",exact:true}).waitFor();
 await c.reload();await c.getByRole("heading",{name:title,exact:true}).waitFor();
 const after=await snapshot();assert.equal(after.homePlan.id,plan.id);assert.equal(after.homePlan.items[0].dosage,"2 spokojne powtórzenia");assert.ok(!JSON.stringify(after).includes(privateText));
 assert.equal((await api(`/rest/v1/home_plans?id=eq.${before.homePlan.id}&select=status`,token))[0].status,"archived");
 await c.screenshot({path:`${dir}/first-guidance-client-mobile.png`,fullPage:true});
 await writeFile(`${dir}/pwd-first-guidance.json`,JSON.stringify({status:"PASS",savedPwdToDraft:true,contextReused:true,privateInterpretationExcluded:true,reviewDateInVersion:true,separateApprovalPublication:true,historyPreserved:true},null,2));
}finally{await browser.close();}
