import assert from "node:assert/strict";
import { mkdir, writeFile } from "node:fs/promises";
import { chromium } from "playwright";
import { api, login } from "./attention_e2e_helpers.mjs";
const id="c7200000-0000-4000-8000-000000000001", dir=process.env.STUDIO_LAS_E2E_ARTIFACT_DIR;
const marker=process.env.STUDIO_LAS_E2E_MARKER, title=`Raport procesu · ${marker}`;
const clientText=`Ustalenia z fikcyjnej współpracy · ${marker}. Wrócimy do omówienia wskazówki na przeglądzie.`;
await mkdir(dir,{recursive:true});
const browser=await chromium.launch();
const tc=await browser.newContext({viewport:{width:1440,height:1000}}),cc=await browser.newContext({viewport:{width:390,height:844}});
const t=await tc.newPage(),c=await cc.newPage();
try{
 const token=await login(t,process.env.STUDIO_LAS_QA_EMAIL,process.env.STUDIO_LAS_QA_PASSWORD,true);
 const clientToken=await login(c,"attention.client@example.test",process.env.STUDIO_LAS_ATTENTION_CLIENT_PASSWORD);
 const snapshot=()=>api("/rest/v1/rpc/client_portal_snapshot",clientToken,"POST",{});
 const initial=await snapshot();
 const pwd=(await api(`/rest/v1/sessions?client_id=eq.${id}&session_type=eq.pwd&order=created_at.desc&limit=1&select=*`,token))[0];assert.ok(pwd);
 const question=(await api(`/rest/v1/guidance_events?client_id=eq.${id}&kind=eq.client_contact_request&order=created_at.desc&limit=1&select=*`,token))[0];assert.ok(question);
 const measuredDate=new Date(Date.now()-10*86400000).toISOString().slice(0,10);
 const measurement=(await api("/rest/v1/body_measurements",token,"POST",{client_id:id,measured_at:measuredDate,source:"Fikcyjny pomiar",weight_kg:70,trainer_interpretation:`Zapis do omówienia · ${marker}`,client_visible:false}))[0];
 await t.getByLabel("Wybierz klienta").selectOption(id);
 await t.getByText("Dostęp klienta do aplikacji: aktywny.",{exact:true}).waitFor();
 await t.getByText("Co zapisano od spotkania lub przeglądu",{exact:true}).click();
 await t.getByLabel("Pokaż zapisy od").selectOption(`session:${pwd.id}`);
 const history=t.locator(".process-history");
 await history.locator(".process-source").filter({hasText:marker}).first().waitFor();
 assert.ok((await history.innerText()).includes("Kontekst pomiaru"));
 await history.screenshot({path:`${dir}/process-changes-desktop.png`});
 await t.setViewportSize({width:390,height:844});assert.equal(await t.evaluate(()=>document.documentElement.scrollWidth>innerWidth+2),false);
 await history.screenshot({path:`${dir}/process-changes-mobile.png`});
 await history.getByRole("link",{name:"Przejdź do materiału na raport",exact:true}).click();
 const form=t.locator(".report-composer form");await form.waitFor();
 for(const source of [pwd.id,initial.homePlan.id,question.id,measurement.id]) await form.locator(`[data-source-id="${source}"] input[type="checkbox"]`).check();
 assert.equal(await form.locator('input[type="checkbox"]:checked').count(),4);
 const fields={title,start_goal:pwd.client_summary,start_capability:"Punkt startowy zapisany w PWD — dane fikcyjne",change:"Zebrano pytanie i zapis pomiaru; nie stwierdzamy na tej podstawie poprawy",interpretation:`Prywatna interpretacja raportu ${marker}`,decision:"Omówić źródła na spotkaniu",current_capability:"Brak nowej udokumentowanej oceny możliwości",next_step:"Powrót do oceny na ustalonym przeglądzie",client_material:clientText};
 for(const [name,value] of Object.entries(fields)) await form.locator(`[name="${name}"]`).fill(value);
 await form.getByRole("button",{name:"Zapisz szkic raportu",exact:true}).click();
 const card=t.locator(".report-record").filter({has:t.getByRole("heading",{name:title,exact:true})});
 await card.getByText("Szkic — nieopublikowany",{exact:true}).waitFor();
 let report=(await api(`/rest/v1/reports?client_id=eq.${id}&title=eq.${encodeURIComponent(title)}&select=*`,token))[0];
 assert.equal(report.evidence_snapshot.length,4);assert.ok(report.evidence_snapshot.some(s=>s.table==="home_plans" && s.date && s.excerpt.includes(initial.homePlan.title)));
 assert.ok(!(await snapshot()).reports.some(r=>r.title===title));
 await card.getByRole("button",{name:"Zatwierdź dokładnie ten raport",exact:true}).click();
 await card.getByRole("button",{name:"Opublikuj zatwierdzony raport",exact:true}).waitFor();
 assert.ok(!(await snapshot()).reports.some(r=>r.title===title));
 await card.getByRole("button",{name:"Opublikuj zatwierdzony raport",exact:true}).click();
 await card.getByText("Opublikowany klientowi",{exact:true}).waitFor();
 const after=await snapshot();assert.equal(after.reports.find(r=>r.title===title).content,clientText);assert.ok(!JSON.stringify(after).includes(`Prywatna interpretacja raportu ${marker}`));
 await c.reload();await c.getByText("Podsumowania postępu",{exact:true}).click();await c.getByText(clientText,{exact:true}).waitFor();
 await card.screenshot({path:`${dir}/process-report-published-mobile.png`});
 await t.reload();await t.getByLabel("Wybierz klienta").selectOption(id);
 await t.locator(".report-record").filter({hasText:title}).waitFor();
 await writeFile(`${dir}/process-report.json`,JSON.stringify({status:"PASS",newVersusOlderContext:true,eventDatePreserved:true,sourceCount:4,sourceTypes:report.evidence_snapshot.map(s=>s.table),serverCapturedEvidence:true,separateApprovalPublication:true,privateNotesExcluded:true,refreshPersistence:true},null,2));
}finally{await browser.close();}
