import assert from "node:assert/strict";
import { collectAttentionSignals, withoutReviewedSignals } from "../assets/os/decision-support.js";
import { collectWorkspaceSignals } from "../assets/os/trainer-signals.js";
const a={id:"session-a",date:"2026-09-09",readiness:2,updated_at:"2026-09-09T10:00:00Z"};
const b={...a,id:"session-b"};
const key=collectAttentionSignals({session:a}).signals[0].signalKey;
const two=collectWorkspaceSignals({sessions:[a,b]});
assert.equal(new Set(two.signals.map(s=>s.signalKey)).size,2,"same-day observations must not collapse");
assert.equal(withoutReviewedSignals(two,[{id:"review",signal_key:key,outcome:"noted_no_change"}]).signals.length,1);
const pending={id:"review",signal_key:key,outcome:"contact_required"};
assert.equal(withoutReviewedSignals(two,[pending]).signals.length,2,"required contact remains open");
assert.equal(withoutReviewedSignals(two,[pending]).signals.find(s=>s.signalKey===key).contactReviewId,"review");
const noOriginal=collectWorkspaceSignals({sessions:[b],signalReviews:[pending]});
assert.ok(withoutReviewedSignals(noOriginal,[pending]).signals.some(s=>s.signalKey===key),"newer source must not hide unresolved contact");
const closed={...pending,contact_resolved_at:"2026-09-09T12:00:00Z"};
assert.ok(!withoutReviewedSignals(two,[closed]).signals.some(s=>s.signalKey===key));
const changed=collectAttentionSignals({session:{...a,updated_at:"2026-09-09T13:00:00Z"}}).signals[0];
assert.notEqual(changed.signalKey,key,"source revision creates new review identity");
const observations=collectWorkspaceSignals({guidanceEvents:[{id:"response-a",event_date:"2026-09-09",created_at:"2026-09-09T12:00:00Z",payload:{note:"Reduced as agreed"}}]});
assert.equal(observations.signals[0].context,"Reduced as agreed");
assert.equal(observations.signals[0].level,"review","narrative is not a failure score");
console.log("SIGNAL_FOLLOWTHROUGH_PASS: exact source, revisions, unresolved contact, narrative evidence");
