import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { stripTypeScriptTypes } from 'node:module';
import vm from 'node:vm';
import { sendInquiryConfirmation } from '../supabase/functions/public-inquiry-ingress/confirmation.ts';
let calls = [], logs = [];
const settings = { INQUIRY_CONFIRMATION_ENABLED: 'true', RESEND_API_KEY: 'test-key', INQUIRY_EMAIL_FROM: 'studio@example.test', INQUIRY_EMAIL_REPLY_TO: 'damian@example.test' };
const deps = { env: key => settings[key], fetch: async (...args) => { calls.push(args); return new Response('{}'); }, log: value => logs.push(value) };
assert.equal(await sendInquiryConfirmation('client@example.test','request-123456',deps),'sent');
const [url, options] = calls[0], body = JSON.parse(options.body);
assert.equal(url,'https://api.resend.com/emails');
assert.deepEqual(body.to,['client@example.test']);
assert.equal(body.reply_to,'damian@example.test');
assert.match(body.from,/^Damian · Studio Las/);
assert.match(body.html,/skontaktuję się z Tobą osobiście/);
assert.match(body.text,/Damian\nTrener · Studio Las/);
assert.equal(options.headers['Idempotency-Key'],'studio-las-inquiry-request-123456');
assert.deepEqual(Object.keys(body).sort(),['from','html','reply_to','subject','text','to']);
calls=[];
assert.equal(await sendInquiryConfirmation(null,'request-123456',deps),'skipped');
assert.equal(await sendInquiryConfirmation('client@example.test','request-123456',{...deps,env:()=>undefined}),'skipped');
assert.equal(calls.length,0);
assert.equal(await sendInquiryConfirmation('client@example.test','request-123456',{...deps,env:k=>k==='INQUIRY_EMAIL_FROM'?'bad\naddress':settings[k]}),'failed');
assert.equal(calls.length,0);
assert.equal(await sendInquiryConfirmation('client@example.test','request-123456',{...deps,fetch:async()=>new Response('',{status:429})}),'failed');
assert.equal(await sendInquiryConfirmation('client@example.test','request-123456',{...deps,fetch:async()=>{throw new Error('secret client@example.test')}}),'failed');
assert(!JSON.stringify(logs).includes('client@example.test'));
// Run the real ingress handler against mocked DB and delivery providers.
let handler, status='created', project='https://ufcumhbnuyernuwepcij.supabase.co', dbError=null, confirmationCalls=0, trainerCalls=0;
let source=readFileSync(new URL('../supabase/functions/public-inquiry-ingress/index.ts',import.meta.url),'utf8').replace(/^import .*;\n/gm,'');
vm.runInNewContext(stripTypeScriptTypes(source),{ Deno:{env:{get:k=>k==='SUPABASE_URL'?project:k==='SUPABASE_SERVICE_ROLE_KEY'?'test-key':undefined},serve:fn=>handler=fn},createClient:()=>({rpc:async()=>({data:{status},error:dbError})}),sendInquiryConfirmation:async()=>{confirmationCalls++},fetch:async()=>{trainerCalls++;return new Response('{}')},crypto:globalThis.crypto,TextEncoder,Response,Request,FormData,AbortSignal,console});
const payload={requestId:'request-123456',name:'Test',phone:'123456789',email:'client@example.test',preferredContactWindow:'16:00–18:00',broadGoal:'Chcę najpierw porozmawiać',contactConsent:true,privacyNoticeVersion:'first-contact-consent-v1',formVersion:'first-contact-v1'};
const request=body=>new Request('https://example.test',{method:'POST',headers:{origin:'https://trenermedycznywarszawa.github.io','content-type':'application/json','x-real-ip':'127.0.0.1'},body:JSON.stringify(body)});
assert.equal((await handler(request(payload))).status,202);
assert.equal(confirmationCalls,1);assert.equal(trainerCalls,1);
status='duplicate';assert.equal((await handler(request(payload))).status,202);
status='rate_limited';assert.equal((await handler(request(payload))).status,429);
assert.equal((await handler(request({...payload,honeypot:'bot'}))).status,202);
assert.equal((await handler(request({...payload,contactConsent:false}))).status,400);
assert.equal(confirmationCalls,1);assert.equal(trainerCalls,1);
status='created';project='https://ulauyoqjoetjqktegeuq.supabase.co';
assert.equal((await handler(request(payload))).status,202);
assert.equal(confirmationCalls,1);assert.equal(trainerCalls,1);
project='https://ufcumhbnuyernuwepcij.supabase.co';dbError=new Error('database failure');
assert.equal((await handler(request(payload))).status,500);
assert.equal(confirmationCalls,1);assert.equal(trainerCalls,1);
console.log('PASS: template, sender, recipient, idempotency, disabled/missing configuration, absent email, provider failures, log privacy and ingress replay/validation behavior');
