-- DEPRECATED / DO NOT EXECUTE
--
-- This file was created with an unsafe migration number.
-- It is intentionally left as a no-op placeholder because the correct migration
-- has been moved to:
--
--   supabase/migrations/011_paper_first_client_checkins.sql
--
-- Reason:
-- The repository already contains another 005 migration:
--   supabase/migrations/005_clients_trainer_write_rls.sql
--
-- Keep this file empty of executable SQL. Do not copy from it. Do not apply it.
